### ISSUE TITLE
Boutons 'controverse précédente et suivante' mettent des controverses aléatoires

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1029]
Par exemple, si on clique une fois sur suivante, et ensuite sur précédente, on ne revient pas à la même.

Je pense que c'est du aux filtres possibles qui changent l'ordre.
Du coup autant mettre un seul bouton 'Controverse suivante', puisque dans tous les cas on peut pas revenir en arrière.
 Sur la page https://www.controversciences.org/timelines/l-39-humanite-peut-elle-se-nourrir-sans-degrader-son-environnement
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Du coup je l'ai corrigé direct dans fichier source, j'avais oublié que je pouvais x)

**Comment by ThibaultLatrille** [comment]
Done
