### ISSUE TITLE
Inviter un ami a découvrir une controverse

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1030]
F. Giry et ControverSciences vous inviteNT à découvrir la controverse : L'humanité peut-elle se nourrir sans dégrader son environnement ?

(manque NT à inviteNT)
 Sur la page https://www.controversciences.org/timelines/22
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
C'est bon du coup je l'ai corrigé dans le dossier source, j'avais oublié que je pouvais !
