### ISSUE TITLE
message recu quand on invite quelqu'un à découvrir la controverse : le bouton-lien bug, il y a deux fois le mot 'la' d'affilé 

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1031]
Dans le bouton lien 'découvrir la la controverse'
 Sur la page https://www.controversciences.org/
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Celui là je l'ai pas trouvé dans le dossier source :(
