### ISSUE TITLE
bug graphique image de "sommes nous capables d'influencer le comportement avec la technologie"

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1037]
Sur la page https://www.controversciences.org/timelines
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
C'est pas la seule, et ca change si on est en mode admin ou pas !

**Comment by florent2602** [comment]
et gros gros bug aussi pour les images de fond dans les controverses à l'affiche en bas de la page d'accueil !!!

**Comment by florent2602** [comment]
J'ai redimensionné quelques photos, ca va mieux mais le problème est toujours là (notamment dans la page d’accueil)
