### ISSUE TITLE
Ajouter des titres en premieres lignes des pages 'vos contributions' 'notification' etc.

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1042]
Pour qu'on sache sur quelle page on est en un coup d'oeil
 Sur la page https://www.controversciences.org/notifications/important
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Sur le modèle de A propos, de la FAQ, par exmemple (tout doit etre homogène en tout cas)
