### ISSUE TITLE
La colonne de gauche apparait en haut depuis cet ordi (un plus petit); c'est normal?

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1099]
Sur la page https://www.controversciences.org/timelines/les-ogm-sont-ils-dangereux-pour-l-environnement
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
C'est quand meme un soucis car du coup sur un petit écran, quand on clique sur une controverse, on voit meme pas le titre et le cadre, il faut scroler toute la page en bas avant d'y arriver !
