### ISSUE TITLE
Les oui/non n'apparaissent pas (et impossible de classer les articles) alors que dans 'ma proposition' ca apparait !

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1314]
Sur la page https://www.controversciences.org/timelines/la-lune-a-t-elle-une-influence-sur-notre-sommeil
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
C'est possible que ca vienne du fait que j'ai modif le titre avec l'éditeur admin et pas des suggestions !

**Comment by ThibaultLatrille** [comment]
C'est corrigé
