### ISSUE TITLE
Ajouter catégorie "rapport institutionnel" dans les références

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1318]
Paul était ok sur Slack, avec vigilance de notre part. Éventuellement mettre un disclaimer dans la description des références qui sont des rapports genre "document non soumis au peer-reviewing"

Il s'agit bien de rapports institutionnels (ministères, onu, etc.) qui sont sérieux quoi, pas un truc de Debout la France sur le nucléaire quoi.
 Sur la page https://www.controversciences.org/timelines/l-elevage-un-avenir-durable-pour-l-environnement
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
En fait non
