### ISSUE TITLE
Quand quelqu'un accepte une correction de faute, ca compte comme une 'nouveauté' générale et pas comme 'quelqu'un a pris en compte votre suggestion'

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1336]
Sur la page https://www.controversciences.org/comments/534
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
En fait c'est bon, c'est juste que "patch frame" apparait au lieu de "les suggestions qui ont été accéptées etc."
