### ISSUE TITLE
Si on veut ajouter dans la synthèse un lien vers une controverse pas encore liée

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1350]
Indiquer : les controverses doivent être liées pour pouvoir naviguer de l'une à l'autre. Si la controverse que vous souhaitez appeler ici n'est pas encore liée, cliquez ici

Et ca renvoit (sur une nouvelle fenetre pour pas perdre le travail) vers la page des liens
 Sur la page https://www.controversciences.org/patches/new?summary_id=16
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
Verifier que c'est pas pareil pour les liens vers des références de la meme controverse :)
