### ISSUE TITLE
Quand on clique sur 'editer son profil', les cases à remplir sont blanches, ca serait mieux si il y avait ce qui est déjà écrit actuellement

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1369]
Sur la page https://www.controversciences.org/users/f-giry/edit
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
Ca fait ca que quand on clique depuis le bouton dans le menu déroullant. Si on clique sur 'editer mon profil' depuis la page du profil ca marche !
