### ISSUE TITLE
le "bienveillant" maintenant ca concerne les suggestions en général, plus que les fautes d'orthographe non ?

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1371]
Il faut changer ce qui aparait quand on met la souris dessus du coup
 Sur la page https://www.controversciences.org/users/63
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
Ha bah cest bon je l'avais déjà modif dans le script apparemment !
