### ISSUE TITLE
voir tous les titres et cadres directement

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1372]
aucun intérêt à ne montrer que le nouveau cadre quand il y a une notif qui dit qu'il y a une nouvelle proposition. Il faudrait bien montrer laquelle est la nouvelle proposition mais tout montrer directement car voter pour une nouvelle contribution comme étant la meilleure, sans voir les autres n'a pas de sens.
 Sur la page https://controversciences.org/frames/210
 Par : N. Clairis
 Navigateur : firefox firefox46 modern windows unknown

**Comment by florent2602** [comment]
Je suis d'accord que ca doit être plus facile d'aller de l'un à l'autre. Par exemple un menu déroulant directement en dessosu du cadre en place "voir les autres cadres" qui permet de voir tous les autres et de voter pour le cas échéant ? sans devoir changer de page.

On pourrait faire pareil pour les analyses et synthèses en fait.
