### ISSUE TITLE
2 contributeurs sur cette analyse, pourtant un seul nom en bas et aucune analyse concurrente. Je pense qu'il manque le 'et al."

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1373]
Sur la page https://www.controversciences.org/references/accelerated-modern-human-induced-species-losses-entering-the-sixth-mass-extinction
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
J'ai fait un test, si on accepte une suggestion y'a bien le 'et al'. Du coup c'est peut etre quand j'ai modif avant des trucs avec l'outil éditeur de l'admin que ca a compté un contributeur en plus mais pas le et.al.

Si c'est ca, il ne faut pas compter un contributeur en plus quand on utilise cet outil ^^
