### ISSUE TITLE
gros BUG suggestions : toutes les modifs demandent à être validée en une fois

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1377]
le texte entier est rouge est un autre texte entier en vert est en dessous.

Ca vient peut etre du fait que j'ai accepté une modif (bouton vert) puis actualisé la page sans enregistrer l'acceptation.
 Sur la page https://www.controversciences.org/patches
 Par : F. Giry
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
Apparemment le bug n'etait que temporaire. Le fait d'accepter proprement d'autres suggestions (d'autres contribution) a résolu le problème
