### ISSUE TITLE
info sur nombre de votes

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#1396]
manque l'info sur le nombre de votes sur chaque cadre... ce serait quand même super informatif histoire de savoir si la différence est de 1 vote ou debeaucoup
 Sur la page https://www.controversciences.org/frames?timeline_id=57
 Par : N. Clairis
 Navigateur : chrome modern windows webkit unknown

**Comment by florent2602** [comment]
Ca serait informatif oui, par contre ca peut faire un effet d'entrainement : les contributions qui ont bcp de votes positifs vont en avoir encore plus (les gens peuvent se dire que c'est pas la peine de lire l'autre).

A voir donc. Même si je suis d'accord que c'est une info interessante ! Peut être ne pas donner le nombre de vote chiffré, mais un visuel ? (genre un visuel si l'écart est large et un autre si l'ecart est sérré)
