### ISSUE TITLE
Add packages dependancies for linux users (postgesql version used, ...)

### ISSUE THREAD

**Issue by alaindanet** [ThibaultLatrille/ControverSciences#848]
I have postgresql 9.4.4 installed and I added the official apt repository of the software.

I have still the same problem than before. I can run controversciences locally but I cannot access to the user_details.

I am looking forward to find the solution.

**Comment by alaindanet** [comment]
pgadmin3 indicates that I have 51 entries in the database table. But I still have not the "user_details" entry which produces the error.

As I said in my previous post, I added the postgresql apt repository to my sources.list, so everything should be up to date for postgresql.

**Comment by ThibaultLatrille** [comment]
Maybe just by reinstalling pg gem ([following this link](http://stackoverflow.com/questions/24379373/how-to-upgrade-postgres-from-9-3-to-9-4-without-losing-data))

$ gem uninstall pg
$ gem install pg

**Comment by alaindanet** [comment]
Now, I have the message:

`Connection refused`

```
  could not connect to server: Connection refused
     Is the server running on host "localhost" (::1) and accepting
     TCP/IP connections on port 5432?
could not connect to server: Connection refused
     Is the server running on host "localhost" (127.0.0.1) and accepting
     TCP/IP connections on port 5432?
```

It's not going better =)

I will take more time to look at it the next week!

Alain.

On 11/08/2015 23:21, Latrille wrote:
>
> Maybe just by reinstalling pg gem (following this link 
> <http://stackoverflow.com/questions/24379373/how-to-upgrade-postgres-from-9-3-to-9-4-without-losing-data>)
>
> $ gem uninstall pg
> $ gem install pg
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ThibaultLatrille/ControverSciences/issues/848#issuecomment-130081693>.
>

-- 
Alain Danet
PhD student in Ecology
Biodicée Lab
University of Montpellier

**Comment by alaindanet** [comment]
I have finally succeed during the brunch!

It was just the port default configuration in postgresql...
