### ISSUE TITLE
Javascript to verify that password and password confirmation are the same

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#867]
The html file that must be modified is views/sessions/new.html.erb
https://github.com/ThibaultLatrille/ControverSciences/blob/master/app/views/users/new.html.erb

The js can be added directly to the html page using 'script' tags.

The CSS is contained in : assets/stylesheets/custom.css.scss
https://github.com/ThibaultLatrille/ControverSciences/blob/master/app/assets/stylesheets/custom.css.scss
Just add the required css at the end of the file

**Comment by alaindanet** [comment]
Ok, I'm in charged of it

**Comment by alaindanet** [comment]
```
<script src="jquery.js"></script>
    <script>
      $(function() {
        // Insérer le code jQuery ici
      });
      </script>
```

**Comment by ThibaultLatrille** [comment]
The tag <script src="jquery.js"></script> is already included in application.html.erb and thus is not necessary.
you will only need
<script>
      $(function() {
        // Insérer le code jQuery ici
      });
      </script>
