### ISSUE TITLE
Quand on vote pour la meilleure intro d'un article par exemple, ca nous redirigie sur une page où il n'y a que l'intro

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#937]
Il faudrait mieux que ca redirige sur la page générale de la référence avec toutes les cases !
 Sur la page https://www.controversciences.org/references/78?filter=my-vote
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Non en fait ca redirige sur "votre analyse préférée". Ca se tient, mais je verrai plutot une redirection vers la page générale quand meme, pour pouvoir continuer la lecture !
