### ISSUE TITLE
Parfois la correction des fautes ne marche pas, meme en God Mode (quand je clique sur 'envoyer', la fenetre ne disparait pas et je peux de nouveau cliquer dessus, à l'infini)

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#939]
Sur la page https://www.controversciences.org/references/89
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
En fait j'ai l'impression que la correction marche, mais je dois fermer la fenêtre manuellement en fait.

**Comment by ThibaultLatrille** [comment]
Toujours le bug ou pas ?

**Comment by florent2602** [comment]
Je te dirai à l'occas, car ca le fait pas tout le temps !
