### ISSUE TITLE
"la source est nécéssaire" quand j'ajoute une photo ET la source

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#940]
Pour les virus, pourtant la controverse a un cadre. Peut etre parce qu'il y a pas de réf ?
 Sur la page https://www.controversciences.org/timelines/les-virus-appartiennent-ils-au-vivant
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
J'ai ajouté un référence, et ca marche toujours pas. Je suis pas chaud pour pousser l'experience en analysant la dite référence là xD

**Comment by ThibaultLatrille** [comment]
C'est corrigé dans la nouvelle version (bug apparu lors de l'ajout des controverses privée)
