### ISSUE TITLE
Tri nombre de like > en fait je sais pas si c'est mieux avec un espace avant le picto xD Je suis relou, oui :p

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#942]
Sur la page https://www.controversciences.org/timelines?sort=nb_likes&tag%5B%5D=
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
En fait il faudra un demi-espace.
