### ISSUE TITLE
blocage 

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#943]
j'ai envoyé le lien du site à une amie en calédo. Le lien ne marche pas... je ne trouve pas d'explication mais c'est pas cool
 Sur la page https://www.controversciences.org/
 Par : P. Guille Escuret
 Navigateur : chrome modern linux webkit

**Comment by alaindanet** [comment]
Whouaw, ça s'est vraiment bizarre!

On 18/08/2015 07:40, Latrille wrote:
>
> j'ai envoyé le lien du site à une amie en calédo. Le lien ne marche 
> pas... je ne trouve pas d'explication mais c'est pas cool
> Sur la page https://www.controversciences.org/
> Par : P. Guille Escuret
> Navigateur : chrome modern linux webkit
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ThibaultLatrille/ControverSciences/issues/943>.
>

-- 
Alain Danet
PhD student in Ecology
Biodicée Lab
University of Montpellier

**Comment by ThibaultLatrille** [comment]
Effectivement très très bizarre, j'ai essayé avec des VPNs un peu partout dans le monde et j'ai pas vu de pbs, peut-être que ca vient de son cache ! Et si elle Ctrl + F5 la page ca fait quoi ?

**Comment by ThibaultLatrille** [comment]
Elle possède une vieille version d'un navigateur qui ne supporte pas les nouveaux certificats SSL (j'ai vérifié). Tu peux lui filer le lien http plutot que https pour que ca marche, mais je lui conseillerai surtout de mettre à jour son navigateur !
