### ISSUE TITLE
Liste des contributeurs > espaces vides

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#950]
Si on descend vite dans la page, il y a des bugs avec des trous dans la maillage, voir meme des cases diformes qui dépassent
 Sur la page https://www.controversciences.org/users
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Les bugs sont dus au fait que certains noms de contributeurs sont en un seul mot collé trop long, du coup ca chie. Lui par exemple : https://www.controversciences.org/users/carlitoenprovencu
