### ISSUE TITLE
Faute "Edt" idem dans la colonne de gauche quand on regarde sa synthèse

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#952]
Sur la page https://www.controversciences.org/summaries?filter=mine&timeline_id=59
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Il faut mettre "Modifier votre synthèse" pour être homogène avec les analyses.
