### ISSUE TITLE
Neutre (quand on situe une référence)

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#959]
Mettre "Neutre(s)" ? Le cas des quotas de peche pas exemple, il y a bénéfiques / nefastes, ca fait bizarre au milieu d'avoir un singulier.
 Sur la page https://www.controversciences.org/timelines/quels-sont-les-effets-de-la-mise-en-place-de-quotas-de-peche-sur-les-populations-de-poissons
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
Ou carrément remplacer neutre par autre chose qui marche avec tout : 

"Ni X ni Y" avec X et Y les deux extrêmes ? Mais c'est un peu long
"Sans avis tranché" ou "Sans conclusions tranchées" ?
"Aucun des deux"
...
