### ISSUE TITLE
couleur du rond d'une référence pas encore placée dans oui/non trop proche des bleus utilisés pour placer entre Oui/non

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#968]
Plutot mettre des ronds oranges quand ils ne sont pas encore placés d'un coté de la controverse ?

(le meme orange que quand une réf n'est pas analysée) ?
Ou une autre couleur sinon, ou alors la couleur 'neutre' par défaut.
 Sur la page https://www.controversciences.org/timelines/98
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
En fait c'est peut etre deja sur la couleur neutre, c'est bon.

Mais il faut vraiment que les couleurs se distinguent mieux dans les ronds. Les 2 couleurs à droite du neutre ca va, mais celles de gauche sont dures a différencier prises une par une, il faut tirer vers le violet bien plus je pense.
