### ISSUE TITLE
Si quelqu'un change son titre / cadre drastiquement alors que c'était la contribution majoritaire, comment on fait ?

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#969]
Ca peut foutre la merde du coup, car en plus on aura meme pas de notification pour etre informé, vu que pour le site ca ne sera pas un changement a signaler.

Au moins, il faut mettre un disclaimer quand on clique sur 'éditer le titre' (en dessous de la place ou on écrit par exemple) en disant de ne pas changer le sens global du titre. On peut aussi remettre les votes a 0 a chaque fois que quelqu'un change, mais ca va vite devenir le merde, ca ne me semble pas etre une bonne idée du tout.
 Sur la page https://www.controversciences.org/timelines/103
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by ThibaultLatrille** [comment]
Effectivement dans ce cas on ne peut que compter sur la bonne foi du contributeur pour ne pas changer le titre de la controverse drastiquement. Après il n'a aucun intérêt à rendre son titre foireux !

**Comment by florent2602** [comment]
Bon bah voui. Je suis d'accord que ce serait vicieux.

Tu peux fermer l'issue du coup ^^
