### ISSUE TITLE
En interne, etablir une liste de mots clés a bannir du site (insultes etc) pour réperer les trolls par un algorithme

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#970]
On alimenterait la liste, et le site indiquerait automatiquement aux admins où ces mots apparaissent. Comme ca c'est simple de repérer les insultes et tout ca qui trainent partout.
 Sur la page https://www.controversciences.org/timelines
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by ThibaultLatrille** [comment]
C'est très compliqué à faire ça au niveau programmation, il faut scanner tout les textes à chaque modif et  regarder les matchs avec la liste des mots clés non permis. Ca demande beaucoup de temps de calcul et ca va vachement ralentir l'application pour les utilisateurs.

**Comment by florent2602** [comment]
Je pensais plus a un outil comme pour 'rechercher', accessible que pour les modo qui marche pour les titres, cadres, analyses etc

Après il doit etre possible de lancer une recherche par mot clé pré-determiné genre 1 fois par semaine non ?

**Comment by ThibaultLatrille** [comment]
Oui c'est possible, faire la recherche une fois par jour et ca ping le slack si il trouve qqch !
C'est pas dans les priorités mais c'est complètement possible ! On aurait un dico des mots interdits qui traîne qq part ?

**Comment by florent2602** [comment]
Ca doit se trouver ^^
Oui je suis d'accord que ce n'est pas pressé !
