### ISSUE TITLE
Rendre fixe la hauteur des rectangles dans la liste des controverses

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#980]
Actuellement il peut varier selon la longueur du titre / cadre.
Le fixer (à la taille max possible aujourd'hui) ferait gagner en homogénéité et ferait plus pro
 Sur la page https://www.controversciences.org/timelines
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by ThibaultLatrille** [comment]
En fait on peut pas fixer la taille car elle dépend de la largeur de l'écran et et des titres de controverses de leurs cadres, calculer la taille max n'est pas possible en fait

**Comment by florent2602** [comment]
Tu peux pas au moins la rendre fixe en hauteur, pour que justement elle ne dépende plus de la taille ?
Parce que la taille max en hauteur est de 3 lignes pour le titre + un espace + 3 lignes pour le cadre + la place pour les picto ... Ca doit etre faisable non ?

Bon c'est pas non plus vital ^^

**Comment by ThibaultLatrille** [comment]
Ce que tu dis est vrai si on considère que la taille de ton écran est la même que celles des écrans de tous les visiteurs ;-) Sur un plus petit écran la taille max du cadre (et du titre) est plus grande. Du coup il faut tout calculer pour tout type d'ecran !

**Comment by florent2602** [comment]
Bah j'avoue que je sais pas comment ca se programme. Je parlais pas forcément en Pixel, mais en lignes quoi ^^ Après est-ce que la taille des lignes est proportionnelle à la taille de l'écran ou fixe ?

Mais bon si tu dis que c'est la merde, je te fais confiance :+1:

**Comment by ThibaultLatrille** [comment]
Yes, un example simple, réduit la largeur de ta fenetre et tu vas voir le bordel que ca va etre

**Comment by florent2602** [comment]
Du coup c'est pareil pour les photos, et c'est pour ca qu'elles sont ne mosaiques ?

**Comment by ThibaultLatrille** [comment]
Exactement

**Comment by florent2602** [comment]
Donc on est condamné à avoir des mosaiques ? x)

**Comment by ThibaultLatrille** [comment]
Je réfléchis et cherche des solutions à ce pb depuis un petit moment et j'ai rien trouvé de bien concluant pour l'instant. Mais j'ai l'espoir de trouver ;-)

**Comment by florent2602** [comment]
Si on considère la photo comme un objet etirable ca marche pas ? Genre on la fixe, et si la fenetre change, la photo se déforme pour suivre. Le soucis c'est que ca peut faire des images toutes dégueues ou floues.

Après vu les photos que je mets qui sont des paysages ou du genre, la mosaique est pas trop crade, c'est pas visuellement aggressif
