### ISSUE TITLE
Dans les menus à dérouler dans enrichir/analyser/synthétiser, les phrases sont au niveau de la flèche si elles occupent moins d'une ligne, et en dessus si elles occupent plus. A homogénéiser :)

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#981]
Sur la page https://www.controversciences.org/empty_summaries
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
C'est pareil partout en fait, meme dans les controverses ! les flèches sont à coté des titres courts mais en dessous des titres longs !

Il faut que la fleche soit toujours dans le coin en haut à droite si possible :)

**Comment by ThibaultLatrille** [comment]
Done
