### ISSUE TITLE
Les nombre d'analyses/synthèses qui est affiché ne doit compter que les publiques

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#982]
Et le nombre de références doit être être celles qui sont analysées

**Comment by florent2602** [comment]
Pour les invités seulement on est d'accord ? ^^

**Comment by ThibaultLatrille** [comment]
Pour tout le monde (sinon c'est un peu la merde niveau info), il suffit de mettre "X références analysées"
