### ISSUE TITLE
Si une reference n'est pas formatée avec les nouveaux [x] dans une synthèse, elle apparait au milieu des autres avec une puce, il faudrait mieux qu'elle soit en dernier

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#984]
Sur la page https://www.controversciences.org/summaries/12
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by ThibaultLatrille** [comment]
C'est trié par ordre d’apparence dans le texte, je sais ce qui est le mieux à vrai dire

**Comment by florent2602** [comment]
Oui oui j'ai vu ! Bah ca se tient, j suis d'accord.
Après visuellement ca fait bizarre.

Bon après pourquoi ils nous feraient chier à mettre des liens sans numéros en plein milieu XD
