### ISSUE TITLE
Dans la page "votre synthèse", toutes les references à la fin après les [x] ne sont pas allignées 

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#985]
Ici la 3 commence plus loin.
Par contre pas de soucis dans la page principale de la controverse :)
 Sur la page https://www.controversciences.org/summaries?filter=mine&timeline_id=62
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by florent2602** [comment]
En fait si ca peut arriver dans la page principale, par exemple la deuxieme de la phytothérapie https://www.controversciences.org/timelines/59

**Comment by florent2602** [comment]
Mais c'est pas les meme que dans la page "ma syntèse", etrange ^^

**Comment by ThibaultLatrille** [comment]
Done
