### ISSUE TITLE
Si on ajoute une référence qui est deja dans la controverse, est-ce qu'un message d'erreur aparait ? Si non, il faut en mettre un :)

### ISSUE THREAD

**Issue by ThibaultLatrille** [ThibaultLatrille/ControverSciences#986]
Sur la page https://www.controversciences.org/timelines
 Par : F. Giry
 Navigateur : chrome modern windows webkit

**Comment by ThibaultLatrille** [comment]
Oui c'est déjà le cas ;-) il regarde le DOI pour ca, comparer les titres n'est pas très efficace (Majuscule, les points, les espaces,... peuvent être differents). C'est un peu la seule raison d'être des DOI sur le site

**Comment by florent2602** [comment]
Ok :)
